# Generated by Django 2.1.5 on 2019-01-22 17:44

from django.db import migrations
from django.utils.timezone import datetime, timedelta

def create_default_templates(apps, schema_editor):
    Invoice = apps.get_model('filterviews', 'Invoice')

    for x in range(10):
        i = Invoice(start_date=   datetime.now() + timedelta(days=x),
                name = "Invoice positive %d"%(x,))
        i.save()

    for x in range(10):
        i = Invoice(start_date=   datetime.now() + timedelta(days=x*-1),
                name = "Invoice negative %d"%(x,))
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('filterviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_templates),
    ]
