# Generated by Django 2.1.5 on 2019-01-09 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCanton', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('codelec', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('nombreProvincia', models.CharField(max_length=34)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.Canton')),
            ],
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('sexo', models.SmallIntegerField()),
                ('fecha_cad', models.DateField()),
                ('junta', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('nombre', models.CharField(max_length=30)),
                ('apellido1', models.CharField(max_length=26)),
                ('apellido2', models.CharField(max_length=26)),
                ('codelec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProvincia', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.Provincia'),
        ),
    ]
