# Generated by Django 2.1.5 on 2019-01-10 01:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('codelec', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('name', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='canton',
        ),
        migrations.RenameField(
            model_name='canton',
            old_name='nombreCanton',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='fecha_cad',
            new_name='cad_date',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='sexo',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='cedula',
            new_name='idCard',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='apellido1',
            new_name='lastname1',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='apellido2',
            new_name='lastname2',
        ),
        migrations.RenameField(
            model_name='elector',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='canton',
            name='provincia',
        ),
        migrations.AlterField(
            model_name='elector',
            name='codelec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.District'),
        ),
        migrations.DeleteModel(
            name='Distrito',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AddField(
            model_name='district',
            name='canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.Canton'),
        ),
    ]
