# Generated by Django 2.1.5 on 2019-01-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0002_auto_20190115_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='stats_female',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='district',
            name='stats_male',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='district',
            name='stats_total',
            field=models.IntegerField(default=-1),
        ),
    ]
