# Generated by Django 2.1.5 on 2019-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0002_auto_20190122_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')], help_text='Hombre o mujer', verbose_name='Genero'),
        ),
    ]
