# Generated by Django 2.1.5 on 2019-01-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0002_auto_20190110_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elector',
            old_name='junta',
            new_name='board',
        ),
        migrations.AddField(
            model_name='canton',
            name='idProvince',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='padronelectoral.Province'),
        ),
        migrations.AddField(
            model_name='elector',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
