# Generated by Django 2.1.5 on 2019-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0003_auto_20190114_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
