# Generated by Django 2.1.5 on 2019-01-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0004_auto_20190114_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canton',
            old_name='idProvince',
            new_name='province',
        ),
    ]
