# Generated by Django 2.1.5 on 2019-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padronelectoral', '0006_auto_20190114_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elector',
            name='lastname1',
        ),
        migrations.RemoveField(
            model_name='elector',
            name='lastname2',
        ),
        migrations.RemoveField(
            model_name='elector',
            name='name',
        ),
        migrations.AlterField(
            model_name='elector',
            name='fullName',
            field=models.CharField(max_length=100),
        ),
    ]
